import Foundation
import CoreGraphics

/// Canvas-level actions a node can dispatch to the app when tapped.
/// These are wired through `AppActionDispatcher` rather than embedded in views
/// so the canvas remains decoupled from navigation and sheet state.
public enum NodeAction: String, Codable, Equatable {
    /// Navigate back to the root home canvas.
    case navigateRoot
    /// Open the app settings sheet.
    case openSettings
    /// Open the user profile sheet.
    case openProfile
    /// Present the CoCaptain AI assistant panel.
    case summonCoCaptain
    /// Present the Pro subscription purchase flow.
    case proSubscription
    /// Open the device-wide project activity history.
    case openActivity
    /// Open today's daily HTML challenges and XP progress.
    case openDaily
}

/// Structural kind of a canvas node, determining its rendering, behavior, and default metadata.
public enum NodeType: String, Codable, Equatable, Hashable, CaseIterable {
    /// A generic node with no special workflow behavior.
    case standard
    /// A node that hosts a runnable HTML/CSS/JS mini-application with its own SRS and code editor.
    case miniApp
    /// A node that acts as a portal to a separate nested canvas.
    case subCanvas
    
    public var displayName: String {
        switch self {
        case .standard: return "Standard"
        case .miniApp: return "Mini-App"
        case .subCanvas: return "Sub-Canvas"
        }
    }

    /// Default palette theme for each workflow node type on the canvas.
    public var defaultTheme: NodeTheme {
        switch self {
        case .miniApp: return .blue
        case .subCanvas: return .cyan
        case .standard: return .indigo
        }
    }

    /// Placeholder title applied when a new node of this type is created.
    public var defaultTitle: String {
        switch self {
        case .miniApp: return "Mini-App"
        case .subCanvas: return "New Canvas"
        case .standard: return "Standard"
        }
    }

    /// Optional subtitle shown below the title in the node card.
    /// `nil` for `.standard` because standard nodes have no fixed workflow subtitle.
    public var defaultSubtitle: String? {
        switch self {
        case .miniApp: return "Tap to run, build, and configure this mini-app."
        case .subCanvas: return "Tap to open this canvas"
        case .standard: return nil
        }
    }

    /// SF Symbol name used for the node card icon when no custom icon is set.
    public var defaultIcon: String {
        switch self {
        case .miniApp: return "app.connected.to.app.below.fill"
        case .subCanvas: return "folder.fill"
        case .standard: return "square.grid.2x2"
        }
    }
}

/// All mutable content owned by a Mini-App node: the SRS specification text,
/// its derived readiness state, the generated HTML/CSS/JS source code, and
/// optional Firebase integration settings.
public struct MiniAppState: Codable, Equatable, Hashable {
    /// Markdown-formatted Software Requirements Specification authored by the user.
    public var srsText: String
    /// Computed readiness level of the current SRS content.
    public var srsReadinessState: SRSReadinessState
    /// Raw HTML/CSS/JS source code for the mini-app, editable directly or generated by CoCaptain.
    public var codeText: String
    /// Last successfully compiled HTML bundle. `nil` if the code has never been compiled.
    public var compiledHTML: String?
    /// Raw Firebase configuration JSON or snippet pasted by the user.
    public var firebaseConfigText: String
    /// Optional Firestore collection/document path used when the mini-app integrates with Firestore.
    public var firebaseFirestorePath: String?
    /// Live HTTPS URL after publishing to GitHub Pages.
    public var publishURL: String?
    /// GitHub username that owns the published repository.
    public var githubRepoOwner: String?
    /// GitHub repository name used for publish.
    public var githubRepoName: String?
    /// GitHub repository numeric id used for republish identity.
    public var githubRepoId: Int?
    /// Timestamp of the most recent successful publish.
    public var publishedAt: Date?
    /// Whether the published GitHub repository is private.
    public var isPublishRepoPrivate: Bool?

    public init(
        srsText: String = SRSScaffold.defaultText,
        srsReadinessState: SRSReadinessState? = nil,
        codeText: String = "",
        compiledHTML: String? = nil,
        firebaseConfigText: String = "",
        firebaseFirestorePath: String? = nil,
        publishURL: String? = nil,
        githubRepoOwner: String? = nil,
        githubRepoName: String? = nil,
        githubRepoId: Int? = nil,
        publishedAt: Date? = nil,
        isPublishRepoPrivate: Bool? = nil
    ) {
        self.srsText = srsText
        self.srsReadinessState = srsReadinessState ?? .empty
        self.codeText = codeText
        self.compiledHTML = compiledHTML
        self.firebaseConfigText = firebaseConfigText
        self.firebaseFirestorePath = firebaseFirestorePath
        self.publishURL = publishURL
        self.githubRepoOwner = githubRepoOwner
        self.githubRepoName = githubRepoName
        self.githubRepoId = githubRepoId
        self.publishedAt = publishedAt
        self.isPublishRepoPrivate = isPublishRepoPrivate
    }
}

/// A single message in a node-scoped CoCaptain conversation.
public struct NodeAgentMessage: Identifiable, Codable, Equatable, Hashable {
    public let id: UUID
    /// The message body text (may contain Markdown).
    public var text: String
    /// `true` when authored by the user; `false` for assistant responses.
    public var isUser: Bool
    public var createdAt: Date

    public init(id: UUID = UUID(), text: String, isUser: Bool, createdAt: Date = Date()) {
        self.id = id
        self.text = text
        self.isUser = isUser
        self.createdAt = createdAt
    }
}

/// Persisted conversation state for a single node's CoCaptain agent.
public struct NodeAgentState: Codable, Equatable, Hashable {
    /// Full ordered message history for this node's agent session.
    public var messages: [NodeAgentMessage]
    /// Compact textual memory injected into the CoCaptain system prompt to
    /// preserve context across sessions without sending the full history.
    public var memorySummary: String?

    public init(messages: [NodeAgentMessage] = [], memorySummary: String? = nil) {
        self.messages = messages
        self.memorySummary = memorySummary
    }
}

/// Programmable identity and behavioral constraints for a node's embedded agent.
public struct AgentProfile: Codable, Equatable, Hashable {
    /// Custom system prompt prepended to every CoCaptain request for this node.
    /// `nil` means the default CoCaptain system prompt is used.
    public var systemPrompt: String?
    /// Display name for the agent's role shown in the CoCaptain panel header.
    public var roleName: String
    /// When `true`, the agent may be triggered automatically by in-app events
    /// rather than requiring explicit user invocation.
    public var isAutoTriggerEnabled: Bool

    public init(systemPrompt: String? = nil, roleName: String = "Assistant", isAutoTriggerEnabled: Bool = false) {
        self.systemPrompt = systemPrompt
        self.roleName = roleName
        self.isAutoTriggerEnabled = isAutoTriggerEnabled
    }
}

/// The core domain entity representing a single node on the CAOCAP spatial canvas.
///
/// A `SpatialNode` is position-aware, themeable, and optionally connected to
/// sibling nodes, nested canvases, or mini-app content. It is the unit of
/// persistence: every project file is a collection of `SpatialNode` values.
public struct SpatialNode: Identifiable, Codable, Equatable {
    public let id: UUID
    /// Structural kind that governs the node's rendering and behavior.
    public var type: NodeType
    /// Absolute position on the infinite canvas coordinate space.
    public var position: CGPoint
    /// User-editable display name shown on the node card.
    public var title: String
    /// Optional secondary description line on the node card.
    public var subtitle: String?
    /// Optional SF Symbol name displayed as the node's icon.
    public var icon: String?
    /// Visual color theme applied to the node card gradient and glow.
    public var theme: NodeTheme
    /// ID of the next node in a sequential flow, used for linear node chains.
    public var nextNodeId: UUID?
    /// IDs of all nodes this node has explicit bidirectional connections to.
    public var connectedNodeIds: [UUID]?
    /// App-level action dispatched when this node is tapped (reserved for system nodes).
    public var action: NodeAction?
    /// Mini-app content and state; only populated for `.miniApp` type nodes.
    public var miniApp: MiniAppState?
    
    /// Persisted node-scoped CoCaptain transcript and compact memory.
    public var agentState: NodeAgentState
    
    /// Programmable identity and behavior rules for this node's agent.
    public var agentProfile: AgentProfile

    /// The filename of the linked canvas for `.subCanvas` nodes.
    public var linkedCanvasFileName: String?
    
    public init(id: UUID = UUID(), type: NodeType = .standard, position: CGPoint, title: String, subtitle: String? = nil, icon: String? = nil, theme: NodeTheme = .blue, nextNodeId: UUID? = nil, connectedNodeIds: [UUID]? = nil, action: NodeAction? = nil, miniApp: MiniAppState? = nil, agentState: NodeAgentState = NodeAgentState(), agentProfile: AgentProfile = AgentProfile(), linkedCanvasFileName: String? = nil) {
        self.id = id
        self.type = type
        self.position = position
        self.title = title
        self.subtitle = subtitle
        self.icon = icon
        self.theme = theme
        self.nextNodeId = nextNodeId
        self.connectedNodeIds = connectedNodeIds
        self.action = action
        self.miniApp = type == .miniApp ? (miniApp ?? MiniAppState()) : miniApp
        self.agentState = agentState
        self.agentProfile = agentProfile
        self.linkedCanvasFileName = linkedCanvasFileName
    }

    /// Returns the node's title after passing it through `LocalizationManager` for
    /// key-based translation when the app is running in a non-English locale.
    public var displayTitle: String {
        LocalizationManager.shared.localizedNodeTitle(title)
    }

    /// Returns the node's subtitle through `LocalizationManager`, or `nil` if no
    /// subtitle is set.
    public var displaySubtitle: String? {
        subtitle.map { LocalizationManager.shared.localizedNodeSubtitle($0) }
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case type
        case position
        case title
        case subtitle
        case icon
        case theme
        case nextNodeId
        case connectedNodeIds
        case action
        case miniApp
        case agentState
        case agentProfile
        case linkedCanvasFileName
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.type = try container.decode(NodeType.self, forKey: .type)
        self.position = try container.decode(CGPoint.self, forKey: .position)
        self.title = try container.decode(String.self, forKey: .title)
        self.subtitle = try container.decodeIfPresent(String.self, forKey: .subtitle)
        self.icon = try container.decodeIfPresent(String.self, forKey: .icon)
        self.theme = try container.decode(NodeTheme.self, forKey: .theme)
        self.nextNodeId = try container.decodeIfPresent(UUID.self, forKey: .nextNodeId)
        self.connectedNodeIds = try container.decodeIfPresent([UUID].self, forKey: .connectedNodeIds)
        // Decode `action` tolerantly: unknown raw values in future formats are silently ignored.
        if let actionString = try container.decodeIfPresent(String.self, forKey: .action) {
            self.action = NodeAction(rawValue: actionString)
        } else {
            self.action = nil
        }
        self.miniApp = try container.decodeIfPresent(MiniAppState.self, forKey: .miniApp)
        // Migration: ensure older saves that predate `MiniAppState` still get a default state.
        if self.type == .miniApp, self.miniApp == nil {
            self.miniApp = MiniAppState()
        }
        self.agentState = try container.decodeIfPresent(NodeAgentState.self, forKey: .agentState) ?? NodeAgentState()
        self.agentProfile = try container.decodeIfPresent(AgentProfile.self, forKey: .agentProfile) ?? AgentProfile()
        self.linkedCanvasFileName = try container.decodeIfPresent(String.self, forKey: .linkedCanvasFileName)
    }

    /// Repairs legacy saves where workflow nodes kept outdated titles, icons, or themes.
    public func applyingCanonicalThemeIfNeeded() -> SpatialNode {
        guard action == nil, type != .standard else { return self }

        var updated = self
        if theme == .blue, type != .miniApp {
            updated.theme = type.defaultTheme
        }

        return updated
    }
}
